kind: "EdgeFunctions"
version: "1"
data:
  functions:
    - name: weather-api-proxy
      origins:
        - name: openweathermap
          domain: api.openweathermap.org
  secrets:
    - key: WEATHER_API_KEY
      value: ${{ WEATHER_API_KEY }}
  # Uncomment to enable a KV store
  # kvs: true
